### PR TITLE
Lots of options

### PR DESCRIPTION
**Pull request by auser**
Added preprocessors, table of contents generation

### CODE REVIEW

**Comment by stefee** [comment]
@auser I'd be really interested to take a look at these changes if you could update the docs/example and get tests passing.

I'm not clear - is this new TOC functionality a generic feature or for your needs specifically?

**Comment by auser** [comment]
@srilq I've updated the PR with fixed tests and README examples.

**Comment by stefee** [comment]
@auser There's an error with running puppeteer in CI that I'm looking into now.

**Comment by stefee** [comment]
@auser Tests are passing on `latest` now, you'll need to rebase onto it and force-push – if you have latest npm it _should_ auto-resolve the package lock conflicts after rebasing.. maybe? Otherwise, just delete the package lock and recreate it with `npm i`. Let me know if there are any issues rebasing!

**Comment by auser** [comment]
@srilq great. This is updated and ready for merge.

**Pull request merged**
